-- Additive Rich recap parity schema, pinned to Go v1.0.0 ent/schema.
-- Nothing here drops, renames, or rewrites an existing table.
-- Identifiers are UUID on PostgreSQL, with the value generated by repositories.
-- Comments must stay free of semicolons because the migrator splits on them.
-- created_at and updated_at are Unix-millisecond integers written by repositories.

CREATE TABLE IF NOT EXISTS telegram_chat_feature_flags (
    id UUID PRIMARY KEY,
    chat_id BIGINT NOT NULL UNIQUE,
    chat_type TEXT NOT NULL,
    chat_title TEXT NOT NULL DEFAULT '',
    feature_chat_histories_recap BOOLEAN NOT NULL DEFAULT FALSE,
    feature_language TEXT NOT NULL DEFAULT '',
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS telegram_chat_recaps_options (
    id UUID PRIMARY KEY,
    chat_id BIGINT NOT NULL UNIQUE,
    auto_recap_send_mode INTEGER NOT NULL DEFAULT 0,
    manual_recap_rate_per_seconds BIGINT NOT NULL DEFAULT 0,
    auto_recap_rates_per_day INTEGER NOT NULL DEFAULT 0,
    pin_auto_recap_message BOOLEAN NOT NULL DEFAULT FALSE,
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0
);

-- Subscribers stay deliberately non-unique: Go inserts without a uniqueness check.
CREATE TABLE IF NOT EXISTS telegram_chat_auto_recaps_subscribers (
    id UUID PRIMARY KEY,
    chat_id BIGINT NOT NULL DEFAULT 0,
    user_id BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS log_chat_histories_recaps (
    id UUID PRIMARY KEY,
    chat_id BIGINT NOT NULL DEFAULT 0,
    recap_inputs TEXT NOT NULL DEFAULT '',
    recap_outputs TEXT NOT NULL DEFAULT '',
    from_platform INTEGER NOT NULL DEFAULT 0,
    prompt_token_usage INTEGER NOT NULL DEFAULT 0,
    completion_token_usage INTEGER NOT NULL DEFAULT 0,
    total_token_usage INTEGER NOT NULL DEFAULT 0,
    recap_type INTEGER NOT NULL DEFAULT 0,
    model_name TEXT NOT NULL DEFAULT '',
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0
);

-- log_id carries the recap log identifier without a foreign key, matching Go.
CREATE TABLE IF NOT EXISTS feedback_chat_histories_recaps_reactions (
    id UUID PRIMARY KEY,
    chat_id BIGINT NOT NULL DEFAULT 0,
    log_id UUID NOT NULL,
    user_id BIGINT NOT NULL DEFAULT 0,
    "type" TEXT NOT NULL DEFAULT 'none' CHECK ("type" IN ('none', 'up_vote', 'down_vote', 'lmao')),
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0
);

-- Retained only so the smr/summarization/feedback/react compatibility callback
-- keeps working. Generation for /smr itself stays out of scope.
CREATE TABLE IF NOT EXISTS feedback_summarizations_reactions (
    id UUID PRIMARY KEY,
    chat_id BIGINT NOT NULL DEFAULT 0,
    log_id UUID NOT NULL,
    user_id BIGINT NOT NULL DEFAULT 0,
    "type" TEXT NOT NULL DEFAULT 'none' CHECK ("type" IN ('none', 'up_vote', 'down_vote', 'lmao')),
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0
);

-- (chat_id, message_id) stays non-unique: one recap sends several parts.
CREATE TABLE IF NOT EXISTS sent_messages (
    id UUID PRIMARY KEY,
    chat_id BIGINT NOT NULL DEFAULT 0,
    message_id INTEGER NOT NULL DEFAULT 0,
    text TEXT NOT NULL DEFAULT '',
    is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
    from_platform INTEGER NOT NULL DEFAULT 0,
    message_type INTEGER NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0
);

-- Go's metric row is append-only and carries no updated_at.
CREATE TABLE IF NOT EXISTS metric_open_ai_chat_completion_token_usages (
    id UUID PRIMARY KEY,
    prompt_operation TEXT NOT NULL DEFAULT '',
    prompt_character_length INTEGER NOT NULL DEFAULT 0,
    prompt_token_usage INTEGER NOT NULL DEFAULT 0,
    completion_character_length INTEGER NOT NULL DEFAULT 0,
    completion_token_usage INTEGER NOT NULL DEFAULT 0,
    total_token_usage INTEGER NOT NULL DEFAULT 0,
    model_name TEXT NOT NULL DEFAULT '',
    created_at BIGINT NOT NULL DEFAULT 0
);

-- Go parity columns for the existing chat_histories table.
-- The integer primary key and every original column are left untouched.
ALTER TABLE chat_histories ADD COLUMN IF NOT EXISTS chat_title TEXT NOT NULL DEFAULT '';
ALTER TABLE chat_histories ADD COLUMN IF NOT EXISTS chat_type TEXT NOT NULL DEFAULT '';
ALTER TABLE chat_histories ADD COLUMN IF NOT EXISTS user_id BIGINT NOT NULL DEFAULT 0;
ALTER TABLE chat_histories ADD COLUMN IF NOT EXISTS username TEXT NOT NULL DEFAULT '';
ALTER TABLE chat_histories ADD COLUMN IF NOT EXISTS full_name TEXT NOT NULL DEFAULT '';
ALTER TABLE chat_histories ADD COLUMN IF NOT EXISTS replied_to_message_id BIGINT NOT NULL DEFAULT 0;
ALTER TABLE chat_histories ADD COLUMN IF NOT EXISTS replied_to_user_id BIGINT NOT NULL DEFAULT 0;
ALTER TABLE chat_histories ADD COLUMN IF NOT EXISTS replied_to_full_name TEXT NOT NULL DEFAULT '';
ALTER TABLE chat_histories ADD COLUMN IF NOT EXISTS replied_to_username TEXT NOT NULL DEFAULT '';
ALTER TABLE chat_histories ADD COLUMN IF NOT EXISTS replied_to_text TEXT NOT NULL DEFAULT '';
ALTER TABLE chat_histories ADD COLUMN IF NOT EXISTS replied_to_chat_type TEXT NOT NULL DEFAULT '';
ALTER TABLE chat_histories ADD COLUMN IF NOT EXISTS chatted_at BIGINT NOT NULL DEFAULT 0;
ALTER TABLE chat_histories ADD COLUMN IF NOT EXISTS embedded BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE chat_histories ADD COLUMN IF NOT EXISTS from_platform INTEGER NOT NULL DEFAULT 0;
ALTER TABLE chat_histories ADD COLUMN IF NOT EXISTS updated_at BIGINT NOT NULL DEFAULT 0;
